name: Package Project

# Controls when the workflow will run
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # get the code under $GITHUB_WORKSPACE directory
      - uses: actions/checkout@v2
      # get the python
      - name: Set up Python 3
        uses: actions/setup-python@v3
      - name: Install deps
        run: pip3 install -r requirements.txt
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export to Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
